# Generated by Django 2.2.27 on 2022-04-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_utility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('publication_time', models.DateTimeField(auto_now_add=True)),
                ('associated_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_utility.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('publication_time', models.DateTimeField(auto_now_add=True)),
                ('associated_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange_utility.Customer')),
            ],
        ),
    ]
