# Generated by Django 2.2.27 on 2022-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_utility', '0002_buyorder_sellorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField()),
                ('quantity', models.FloatField(default=1e-08)),
                ('price', models.FloatField(default=0.01)),
                ('choice_change', models.CharField(default='MODIFICA', max_length=8)),
            ],
        ),
    ]
